version: '3'
services:
  frontend:
    build: ./
    image: frontend
    container_name: frontend
    networks:
      - capstone-network
    restart: always

networks:
  capstone-network:
    external:
     name: capstone-network