version: '3.7'

volumes:
  node_modules: 
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    # networks:
    #   - capstone-network
    restart: always
    
networks:
  default:
    name: capstone-network
    external: true