version: '3'

volumes:
  node_modules: 
services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ../../Files:/usr/src/app/public
    ports:
      - 3000:3000
    restart: always
    
networks:
  default:
    name: capstone-network
    external: true