version: '3'
services:
  backend:
    container_name: backend ##ชื่อ Container จะเอาไปเชื่อมกับ Nginx.conf ที่ส่วน Server:8080
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database/bannarug?serverTimezone=UTC
    ports:
      - 8080:8080
    restart: always

networks:
  default:
    name: capstone-network
    external: true