version: '3.8'
services:
  backend:
    container_name: backend ##ชื่อ Container จะเอาไปเชื่อมกับ Nginx.conf ที่ส่วน Server:8080
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    networks:
      - capstone-network
    restart: always

networks:
  capstone-network:
    external:
     name: capstone-network