version: '3'
services:
  database:
    container_name: database
    image: mysql:latest
    expose:
      # - 3307:3306
      - 3306
    volumes:
      - ./bannarug.sql:/docker-entrypoint-initdb.d/bannarug.sql
      - ../../mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=CP23ej2
      - LANG=en_US.UTF-8
    restart: always

networks:
  default:
    name: capstone-network
    external: true