version: '3'
services:
  proxy:
    container_name: reverse_proxy
    image: nginx:1.19.1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:cached
      # - ./logs/:/var/log/nginx:cached
      - ./cert/:/etc/nginx/ssl/
    ports:
      - 80:80
      - 443:443
    restart: always


networks:
  default:
    name: capstone-network
    external: true