version: '3.7'
services:
  proxy:
    container_name: reverse_proxy
    image: nginx
    ports:
      - 80:80
      - 443:443
    # networks:
    #   - capstone-network
    volumes:
      - ./cert/:/etc/nginx/ssl/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    

networks:
  default:
    name: capstone-network
    external: true