version: '3.7'
services:
  proxy:
    container_name: reverse_proxy
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    # networks:
    #   - capstone-network
    volumes:
      - ./cert/cp23ej2.crt:/etc/nginx/ssl/cp23ej2.crt:ro
      - ./cert/cp23ej2.csr.txt:/etc/nginx/ssl/cp23ej2.csr.txt:ro
      - ./cert/cp23ej2.key.txt:/etc/nginx/ssl/cp23ej2.key.txt:ro
      - ./cert/cp23ej2.pem.txt:/etc/nginx/ssl/cp23ej2.pem.txt:ro
      # - ./cert/:/etc/nginx/ssl/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx:cached
    restart: always
    

networks:
  default:
    name: capstone-network
    external: true