name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      # Delete Directory File And Back Up Database
      # - name: Delete Directory
      #   run: |
      #     cd ..
      #     sudo rm -rf Files 

      # Runs a Database  
      - name: Database Docker Compose Down and Remove Images
        run: |
          cd database
          docker compose down
          docker rmi -f database
          docker compose up -d --build
          docker image prune -f
          cd ..

      # Runs a Back-end
      - name: Back-end Docker Compose Down and Remove Images
        run: |
          cd backend
          docker compose down
          docker rmi -f backend
          docker compose up -d --build
          docker image prune -f
          cd ..
      
      # Runs a Front-end
      - name: Front-end Docker Compose Down and Remove Images
        run: |
          cd frontend
          docker compose down
          docker rmi -f frontend
          docker compose up -d --build
          docker image prune -f
          cd ..
