name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      # Delete Directory File And Back Up Database
      - name: Delete Directory
        run: |
          cd ..
          sudo rm -rf mysql-data
          sudo rm -rf Files

      # Runs a Database  
      - name: Database Docker Compose Down and Remove Images
        run: |
          cd database
          sudo docker compose down
          sudo docker rmi -f database
          sudo docker compose up -d --build
          sudo docker image prune -f
          cd ..

      # Runs a Back-end
      - name: Back-end Docker Compose Down and Remove Images
        run: |
          cd backend
          sudo docker compose down
          sudo docker rmi -f backend
          sudo docker compose up -d --build
          sudo docker image prune -f
          cd ..
      
      # Runs a Front-end
      - name: Front-end Docker Compose Down and Remove Images
        run: |
          cd frontend
          sudo docker compose down
          sudo docker rmi -f frontend
          sudo docker compose up -d --build
          sudo docker image prune -f
          cd ..
